export const LOGS = {
  frp: {
    notExistConfig: "Нет конфига FRP - доступ только в локальной сети",
    start: "Запускаю FRP...",
    exit: "FRP-клиент отключился с кодом",
    fail: "Не удалось запустить FRP",
  },
  base: {
    start: "=== Запускаю родительский контроль ===",
    started: "=== Родительский контроль запущен ===",
    platform: "Платформа ОС",
    node: "Версия движка js",
    user: "Пользователь",
    webPortUsed: "Веб-сервер не может быть запущен!",
    remoteStarted: "Удаленный сервер запущен на порту: ",
    networkError: "Ошибка сети, проверьте подключение к интернету.",
    url: "Веб-интерфейс: http://",
    panel: "Удаленный контроль: telnet",
    uncaughtException: "Необработанное исключение",
    uncaughtError: "Необработанная ошибка",
    startupError: "Ошибка запуска",
    shutdown: "\n=== Выключение родительского контроля ===",
    shutdownEnd: "Родительский контроль деактивирован",
    fatal: "Глобальная ошибка",
    second: "сек.",
    minute: "мин.",
    hour: "ч.",
    msgButtonText: "OK",
    client: "Клиент",
    usedPort: (port) => `Порт ${port} занят!`,
    portLog: (start, port, end) => `${start} ${port} ${end}`,
  },
  control: {
    init: "Инициализация родительского контроля для",
    monit: "Ведется мониторинг пользователя",
    unmonit: "исключен из мониторинга",
    stateLoadError: "Ошибка загрузки состояния:",
    newDayReset: "Сброс таймеров по смене суток",
    stateLoaded: "Состояние загружено",
    stateSaved: "Состояние успешно сохранено",
    stateSavedError: "Ошибка сохранения состояния",
    getStateError: "Ошибка получения состояния блокировки",
    stateStats: "время блокировки, лимит использования:",
    lock: "ПК успешно заблокирован",
    noWinLock: "Блокировка ПК не поддерживается платформой",
    lockError: "Ошибка блокировки ПК:",
    shutdownTimeout: "Выключение запланировано через",
    shutdownError: "Ошибка отложенного выключения",
    shutdownAbort: "Выключение отменено",
    shutdownAbortError: "Ошибка отмены выключения",
    showMessageError: "Ошибка отображения сообщения:",
    badTime: "Неправильный формат времени",
    lockTimeout: "Добавлена отложенная блокировка",
    positiveTime: "Минуты должны быть положительными",
    limit: "Установлен лимит использования",
    unlock: "ПК разблокирован",
    monitError: "Ошибка мониторинга:",
    monitStart: "Мониторинг запущен",
    remoteLock: "Достигнуто время отложенной блокировки",
    useLimit: "Достигнут дневной лимит в",
    sendWarn: "Отправлено предупреждение:",
    stop: "Родительский контроль остановлен.",
    lockMessageTimeout: (time) =>
      `⚠️ Компьютер будет заблокирован через ${time} минут!`,
  },
  remote: {
    connect: "Клиент подключен",
    wsErr: "Ошибка веб-сокет",
    disconnect: "отключился",
    command: "Команда от клиента",
    commandError: "Ошибка запуска команды",
    responseError: "Ошибка отправки ответа",
    disconnectError: "Ошибка разрыва соединения с клиентом",
    stop: "Удаленный сервер остановлен",
    unlimit: "Нет установленных лимитов",
    lock: "ПК заблокирован",
    shutdown: "ПК выключен",
    shutdownDelay: "ПК выключится в течении 10 секунд",
    shutdownAbort: "Выключение отменено",
    lock_m: "ЗАЛОЧЕН",
    unlock_m: "РАЗЛОЧЕН",
    lockTimes: "Нет",
    invalidLimit: "Некорректное значение лимита",
    setLimit: "Установлен лимит использования",
    badTime: "Некорректный формат (используйте ЧЧ:ММ)",
    addLock: "Время блокировки добавлено",
    invalidTime: "Некорректный формат времени",
    noLimitExtend: "Не установлен лимит для продления",
    timeExtend: "Лимит увеличен до",
    clearLimit: "Лимит использования очищен",
    clearLockTimes: "Отложенные блокировки очищены",
    clearAll: "Лимиты и отложенные блокировки очищены",
    unknown: "Неизвестная команда (воспользуйтесь HELP)",
    available: `Допустимые команды:
      LOCK                    - Заблокировать ПК
      SHUTDOWN                - Выключить ПК через минуту
      SHUTDOWN_NOW            - Выключить ПК через 10 секунд
      CANCEL_SHUTDOWN         - Отмена отложенного выключения
      GET_NAME                - Получить имя ПК
      GET_CURRENT_USER        - Получить имя текущего пользователя
      GET_STATUS              - Проверка блокировки ПК
      GET_USAGE_LIMIT         - Получить текущий лимит использования
      GET_LOCK_TIMES          - Получить время отложенной блокировки
      GET_TIME_REMAINING      - Получить время до блокировки
      GET_USAGE_TIME          - Получить время использования
      MESSAGE:<text>          - Отправить сообщение
      SET_LIMIT:<minutes>     - Установить лимит использования
      ADD_LOCK_TIME:HH:MM     - Добавить отложенную блокировку
      EXTEND_TIME:<minutes>   - Увеличить время использования
      CLEAR_USAGE_LIMIT       - Удалить лимит
      CLEAR_LOCK_TIMES        - Удалить отложенные блокировки
      CLEAR_ALL               - Удалить все лимиты и отложенные действия
      HELP                    - Получить список доступных команд`,
  },
  user: {
    firewall: "Проверьте свой брандмауэр или другие приложения.",
    lock: "🔒 ЗАБЛОКИРОВАН",
    unlock: "🟢 РАЗБЛОКИРОВАН",
    online: "🟢 ОНЛАЙН",
    emptyNetwork: "В сети нет обнаруженных ПК.",
    emptyNetworkHint:
      "Убедитесь, что агент PC Time Control запущен на других компьютерах.",
    title: "Родительский контроль ПК",
    agentsOn: "🟢 Удаленные агенты онлайн",
    agentsOff: "⚠️ Удаленные агенты оффлайн",
    find: "🔍 Поиск устройств",
    refresh: "🔄 Обновить статус",
    available: "Доступные ПК:",
    last: "Последняя проверка:",
    yet: "Ещё не отсканировано",
    absent: "отсутствуют",
    unlimit: "Ограничения не установлены",
    timeRemaining: "Время напоминания",
    control: "Управление",
    back: "← Назад",
    settings: "📊 Текущие настройки",
    dayLimit: "Суточный лимит",
    notSet: "не задан",
    delayLocks: "Отложенные блокировки",
    resetLimits: "🗑️ Убрать ограничения",
    scan: "🔍 Сканирую...",
    update: "🔄 Обновляю...",
    confirm: "⚠️ Точно выключаем?",
    mess: "Введите текст сообщения",
    sent: "✅ Сообщение отправлено",
    error: "❌ Ошибка: ",
    minInput: "Введите минуты",
    timeSelect: "Выберите время",
    resAllConf:
      "⚠️ Точно хотите сбросить все лимиты и удалить отложенные блокировки?",
    now: "🔒 Немедленные действия",
    lockNow: "🔒 Заблокировать",
    shutdown: "⏻ Выключить",
    sendMsg: "💬 Отправить сообщение",
    messPlaceholder: "Введите текст...",
    send: "Отправить",
    setLimit: "⏱️ Установить ограничение",
    halfHour: "30 минут",
    hour: "1 час",
    hours: " часа",
    timePlaceholder: "Или введите минуты...",
    saveLimit: "Задать ограничитель",
    delayLock: "🕐 Отложенная блокировка",
    delayLockSave: "Утвердить время блокировки",
  },
  web: {
    started: "Веб-сервер запущен на порту",
    stopped: "Веб-сервер остановлен",
    httpErr: "Ошибка HTTP:",
    scan: "Начинаю сканирование сети",
    scanEnd: "Сканирование сети завершено, найдено ПК:",
    failCon: "Ошибка соединения",
    scanErr: 'Ошибка сканирования',
    refreshErr: 'Ошибка обновления'
  },
};

export const PATHS = {
  library: "node_modules/@qiudaomao/node-frp/src/cli.js",
  config: "frpc.yaml",
  localhost: "127.0.0.1",
  commands: {
    logon: 'tasklist /FI "IMAGENAME eq LogonUI.exe" /NH',
    lock: "rundll32.exe user32.dll,LockWorkStation",
    shutdownAbort: "shutdown /a",
    getPid: 'netstat -ano | findstr',
    cleanPort: 'taskkill /F /PID',
    sendMess: (message, title, button) =>
      `powershell -Command "Add-Type -AssemblyName System.Windows.Forms; [System.Windows.Forms.MessageBox]::Show('${message}', '${title}', '${button}', 'Warning')"`,
    shutdownWin: (seconds) =>
      `shutdown /s /t ${seconds} /c "Computer will shutdown in ${seconds} seconds"`,
    shutdown: (timeout) => `shutdown -h +${timeout}`,
  },
};
